<a href="https://colab.research.google.com/github/marynatarasevych/ML_Study/blob/main/Tarasevych_%22HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8)_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [35]:
import random
import numpy as np
np.array([random.uniform(0, 1) for _ in range(10)])

array([0.78863855, 0.9382693 , 0.87951487, 0.28048129, 0.9909249 ,
       0.75700166, 0.24484319, 0.41882294, 0.19995125, 0.9628971 ])

random.uniform - створює тільки 1 число, тому вектор треба створювати через цикл

In [36]:
import numpy as np
vector = np.random.rand(10)
vector, vector.shape

(array([0.86448586, 0.24548989, 0.67693077, 0.68695956, 0.56194637,
        0.36278998, 0.22416692, 0.65977858, 0.25141726, 0.15822113]),
 (10,))

np.random.rand - створює вектор або матрицю з числами від 0 до 1

In [37]:
matrix = np.array([[11,14,17],
                  [20,23,26],
                  [29,32,35]])
matrix, matrix.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))

Розмірність матриці - 3х3


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [38]:
np.round(vector+10,2)

array([10.86, 10.25, 10.68, 10.69, 10.56, 10.36, 10.22, 10.66, 10.25,
       10.16])

In [39]:
matrix*2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [40]:
vector**2

array([0.7473358 , 0.06026529, 0.45823527, 0.47191343, 0.31578372,
       0.13161657, 0.05025081, 0.43530778, 0.06321064, 0.02503392])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [41]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [42]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [ ]:
Розмір результуючої матриці - m x p. Тому якщо поміняти матриці 3х2 та 2х3 місцями, то результат буде 2х2

In [43]:
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

In [44]:
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [45]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [46]:
vector.T

array([0.86448586, 0.24548989, 0.67693077, 0.68695956, 0.56194637,
       0.36278998, 0.22416692, 0.65977858, 0.25141726, 0.15822113])

Змін немає в NumPy немає, але в математиці транспонування вектора може мати сенс, коли потрібно рядок перевернути в стопвчик і навпаки

In [48]:
column_vector = np.expand_dims(vector, axis=1)
column_vector

array([[0.86448586],
       [0.24548989],
       [0.67693077],
       [0.68695956],
       [0.56194637],
       [0.36278998],
       [0.22416692],
       [0.65977858],
       [0.25141726],
       [0.15822113]])

Тепер перевернувся в стовпець :)

In [51]:
column_vector.T, column_vector.T.shape

(array([[0.86448586, 0.24548989, 0.67693077, 0.68695956, 0.56194637,
         0.36278998, 0.22416692, 0.65977858, 0.25141726, 0.15822113]]),
 (1, 10))

На початку додались `([` і тепер це матриця з розмірністю 1 х 10

У вектора розмірність була (10,)